import type { Widget, ProjectType } from '../store/useStore';
import type { Node, Edge } from '@xyflow/react';
import { getPlugin } from '../plugins/registry';

const hexToRaylibColor = (hex: string) => {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `(Color){ ${r}, ${g}, ${b}, 255 }`;
};

const sanitize = (name: string) => name.replace(/[^a-zA-Z0-9_]/g, '_');
const prop = <T>(v: unknown, fallback: T): T => (v !== undefined && v !== null ? v as T : fallback);

export const generateCCode = (widgets: Widget[], nodes: Node[], edges: Edge[], projectType: ProjectType = 'gui', pluginId = 'none', uiLibrary = 'none'): string => {
  const lines: string[] = [];
  const raylib = uiLibrary === 'raylib';
  const cimgui = uiLibrary === 'cimgui';
  const plugin = getPlugin(pluginId);

  if (raylib) {
    lines.push(`#include "raylib.h"`);
    lines.push(`#include "raygui.h"`);
  }
  if (cimgui) {
    lines.push(`#include "cimgui.h"`);
    lines.push(`#include "imgui_impl_glfw.h"`);
    lines.push(`#include "imgui_impl_opengl3.h"`);
    lines.push(`#include <GLFW/glfw3.h>`);
  }
  plugin.headers.forEach(h => lines.push(h));
  lines.push(`#include <stdio.h>`);
  lines.push(`#include <stdbool.h>`);
  lines.push(`#include <string.h>`);
  lines.push(`#include <stdlib.h>`);
  lines.push(`#include <unistd.h>`);
  lines.push(`#include <time.h>`);
  lines.push(``);

  if (raylib || cimgui) {
    lines.push(`#define SCREEN_WIDTH 800`);
    lines.push(`#define SCREEN_HEIGHT 600`);
    lines.push(``);
  }

  if (projectType === 'library') {
    lines.push(`// ====================================================`);
    lines.push(`//  ${sanitize('library')}.h — Public API`);
    lines.push(`//  (auto-generated by C-Builder)`);
    lines.push(`// ====================================================`);
    lines.push(``);
  }

  // Collect variable names from SetVar/GetVar nodes
  const varNodes = nodes.filter(n =>
    n.data.label === 'Set Variable' || n.data.label === 'Get Variable'
  );
  const varNames = new Set<string>();
  varNodes.forEach(n => {
    const name = (n.data.varName as string) || `var_${n.id.slice(0, 4)}`;
    varNames.add(sanitize(name));
  });

  // Global variables
  if (varNames.size > 0) {
    lines.push(`// Variables`);
    varNames.forEach(v => lines.push(`int ${v} = 0;`));
    lines.push(``);
  }

  // TextField state variables (only for UI lib types)
  if (raylib || cimgui) {
    const textFields = widgets.filter(w => w.type === 'TextField');
    if (textFields.length > 0) {
      lines.push(`// TextField buffers`);
      textFields.forEach(w => {
        lines.push(`char ${sanitize(w.name)}_buf[256] = "";`);
        lines.push(`int ${sanitize(w.name)}_len = 0;`);
      });
      lines.push(``);
    }
  }

  // Slider state variables (only for UI lib types)
  if (raylib || cimgui) {
    const sliders = widgets.filter(w => w.type === 'Slider');
    if (sliders.length > 0) {
      lines.push(`// Slider values`);
      sliders.forEach(w => {
        const def = prop(w.properties.min, 0);
        lines.push(`float ${sanitize(w.name)}_value = ${def};`);
      });
      lines.push(``);
    }
  }

  // Logic traversal helpers
  const findNextNode = (nodeId: string, handle = 'exec_out') => {
    const edge = edges.find(e =>
      e.source === nodeId && (e.sourceHandle === handle || e.sourceHandle === null || e.sourceHandle === undefined)
    );
    return edge ? nodes.find(n => n.id === edge.target) ?? null : null;
  };

  const dataVars = new Map<string, string>();
  let varCounter = 0;
  const declareVar = (nodeId: string) => {
    const v = `_t${varCounter++}`;
    dataVars.set(nodeId, v);
    return v;
  };
  const getVar = (nodeId: string) => dataVars.get(nodeId) ?? declareVar(nodeId);

  const getDataValueC = (nodeId: string, inputHandle: string): string => {
    const edge = edges.find(e => e.target === nodeId && e.targetHandle === inputHandle);
    if (!edge) return '0';
    const src = nodes.find(n => n.id === edge.source);
    if (!src) return '0';
    const sl = src.data.label as string;

    if (sl === 'Get Variable') {
      const name = (src.data.varName as string) || `var_${src.id.slice(0, 4)}`;
      return sanitize(name);
    }
    if (sl === 'Add' || sl === 'Subtract' || sl === 'Multiply' || sl === 'Divide' || sl === 'Modulo') {
      const a = getDataValueC(src.id, 'a');
      const b = getDataValueC(src.id, 'b');
      const op = sl === 'Add' ? '+' : sl === 'Subtract' ? '-' : sl === 'Multiply' ? '*' : sl === 'Divide' ? '/' : '%';
      return `(${a} ${op} ${b})`;
    }
    if (sl === 'Greater Than') {
      const a = getDataValueC(src.id, 'a');
      const b = getDataValueC(src.id, 'b');
      return `(${a} > ${b})`;
    }
    if (sl === 'Less Than') {
      const a = getDataValueC(src.id, 'a');
      const b = getDataValueC(src.id, 'b');
      return `(${a} < ${b})`;
    }
    if (sl === 'Equals') {
      const a = getDataValueC(src.id, 'a');
      const b = getDataValueC(src.id, 'b');
      return `(${a} == ${b})`;
    }
    if (sl === 'String Equals') {
      const a = getDataValueC(src.id, 'a');
      const b = getDataValueC(src.id, 'b');
      return `(strcmp(${a}, ${b}) == 0)`;
    }
    if (sl === 'And') {
      const a = getDataValueC(src.id, 'a');
      const b = getDataValueC(src.id, 'b');
      return `(${a} && ${b})`;
    }
    if (sl === 'Or') {
      const a = getDataValueC(src.id, 'a');
      const b = getDataValueC(src.id, 'b');
      return `(${a} || ${b})`;
    }
    if (sl === 'Not') {
      const a = getDataValueC(src.id, 'a');
      return `(!${a})`;
    }
    if (sl === 'String Length') {
      const s = getDataValueC(src.id, 'str');
      return `(int)strlen(${s})`;
    }
    if (sl === 'String to Int') {
      const s = getDataValueC(src.id, 'str');
      return `atoi(${s})`;
    }
    if (sl === 'String Concat') {
      return getVar(src.id);
    }
    if (sl === 'Allocate Memory') {
      return getVar(src.id);
    }
    if (sl === 'Get Time (ms)') {
      return getVar(src.id);
    }
    if (sl === 'Read Integer') {
      return getVar(src.id);
    }
    // Fallback: check if this node has a data output and a declared variable
    const v = dataVars.get(src.id);
    if (v) return v;
    return String(src.data.value ?? '0');
  };

  const generateNodeCode = (node: Node, indent = '    '): string => {
    const label = node.data.label as string;
    let code = '';

    if (label === 'Print String') {
      const str = (node.data.stringValue as string) || 'Hello';
      if (raylib) {
        code += `${indent}TraceLog(LOG_INFO, "${str}");\n`;
      } else {
        code += `${indent}printf("%s\\n", "${str}");\n`;
      }
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'Printf') {
      const fmt = (node.data.format as string) || '%d\\n';
      const val = getDataValueC(node.id, 'value');
      code += `${indent}printf("${fmt}", ${val});\n`;
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'Branch') {
      const cond = getDataValueC(node.id, 'condition');
      code += `${indent}if (${cond}) {\n`;
      const trueNode = findNextNode(node.id, 'true');
      if (trueNode) code += generateNodeCode(trueNode, indent + '    ');
      code += `${indent}} else {\n`;
      const falseNode = findNextNode(node.id, 'false');
      if (falseNode) code += generateNodeCode(falseNode, indent + '    ');
      code += `${indent}}\n`;
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'For Loop') {
      const start = getDataValueC(node.id, 'start');
      const end = getDataValueC(node.id, 'end');
      code += `${indent}for (int i = ${start}; i < ${end}; i++) {\n`;
      const body = findNextNode(node.id, 'loop_body');
      if (body) code += generateNodeCode(body, indent + '    ');
      code += `${indent}}\n`;
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'While Loop') {
      const cond = getDataValueC(node.id, 'condition');
      code += `${indent}while (${cond}) {\n`;
      const body = findNextNode(node.id, 'loop_body');
      if (body) code += generateNodeCode(body, indent + '    ');
      code += `${indent}}\n`;
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'Set Variable') {
      const name = sanitize((node.data.varName as string) || `var_${node.id.slice(0, 4)}`);
      const val = getDataValueC(node.id, 'value');
      code += `${indent}${name} = ${val};\n`;
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'Add' || label === 'Subtract' || label === 'Multiply' || label === 'Divide') {
      // Math nodes generate their expression inline via getDataValueC
      // exec flow just passes through to the next node
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'Delay (ms)') {
      const ms = getDataValueC(node.id, 'ms');
      code += `${indent}usleep((${ms}) * 1000);\n`;
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'Modulo') {
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'String Length' || label === 'String to Int') {
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'String Concat') {
      const a = getDataValueC(node.id, 'a');
      const b = getDataValueC(node.id, 'b');
      const v = declareVar(node.id);
      code += `${indent}char ${v}[512];\n`;
      code += `${indent}snprintf(${v}, sizeof(${v}), "%s%s", ${a}, ${b});\n`;
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'Allocate Memory') {
      const size = getDataValueC(node.id, 'size');
      const v = declareVar(node.id);
      code += `${indent}void *${v} = malloc(${size});\n`;
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'Free Memory') {
      const ptr = getDataValueC(node.id, 'ptr');
      code += `${indent}free((void*)${ptr});\n`;
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'Get Time (ms)') {
      const v = declareVar(node.id);
      code += `${indent}long long ${v} = (long long)(clock() * 1000 / CLOCKS_PER_SEC);\n`;
      // Time is an output-only node, no exec flow typically
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else if (label === 'Read Integer') {
      const prompt = (node.data.prompt as string) || '';
      const v = declareVar(node.id);
      if (prompt) code += `${indent}printf("${prompt}");\n`;
      code += `${indent}int ${v};\n`;
      code += `${indent}scanf("%d", &${v});\n`;
      const next = findNextNode(node.id, 'exec_out');
      if (next) code += generateNodeCode(next, indent);

    } else {
      // Fallback: treat unknown nodes as C function calls
      const funcName = label.replace(/[^a-zA-Z0-9_]/g, '_');
      const outputs = (node.data as Record<string, unknown>).outputs as { id: string; type?: string }[] | undefined;
      const hasDataOutput = outputs?.some(o => o.type !== 'exec');
      const hasExecInput = (node.data as Record<string, unknown>).inputs instanceof Array &&
        ((node.data as Record<string, unknown>).inputs as { type?: string }[]).some(i => i.type === 'exec');
      const hasExecOutput = outputs?.some(o => o.type === 'exec');

      if (hasDataOutput && !hasExecInput) {
        // Pure data node (no exec flow) — just declare a variable for its result
        const v = declareVar(node.id);
        const params: string[] = [];
        const inputs = (node.data as Record<string, unknown>).inputs as { id: string }[] | undefined;
        if (inputs) {
          inputs.forEach(inp => params.push(getDataValueC(node.id, inp.id)));
        }
        code += `${indent}int ${v} = ${funcName}(${params.join(', ')});\n`;
      } else if (hasExecInput) {
        // Exec node — generate as statement
        const params: string[] = [];
        const inputs = (node.data as Record<string, unknown>).inputs as { id: string }[] | undefined;
        if (inputs) {
          inputs.forEach(inp => {
            if (inp.id !== 'exec_in') params.push(getDataValueC(node.id, inp.id));
          });
        }
        if (hasDataOutput) {
          const v = declareVar(node.id);
          code += `${indent}int ${v} = ${funcName}(${params.join(', ')});\n`;
        } else {
          code += `${indent}${funcName}(${params.join(', ')});\n`;
        }
        if (hasExecOutput) {
          const next = findNextNode(node.id, 'exec_out');
          if (next) code += generateNodeCode(next, indent);
        }
      }
    }

    return code;
  };

  // Button event handlers (only for UI lib types)
  if (raylib || cimgui) {
    const buttons = widgets.filter(w => w.type === 'Button');
    buttons.forEach(w => {
      lines.push(`void On_${sanitize(w.name)}_Clicked(void) {`);
      const eventNode = nodes.find(n =>
        n.data.label === 'On Clicked (Button)'
      );
      if (eventNode) {
        const next = findNextNode(eventNode.id, 'exec');
        if (next) lines.push(generateNodeCode(next).trimEnd());
      } else {
        lines.push(`    printf("Button ${w.name} clicked\\n");`);
      }
      lines.push(`}`);
      lines.push(``);
    });
  }

  const onStartNode = nodes.find(n => n.data.label === 'On Start');

  // Library type: emit declarations only (implementation goes in .c file)
  if (projectType === 'library') {
    if (onStartNode) lines.push(`void OnStart(void);`);
    const buttons = widgets.filter(w => w.type === 'Button');
    buttons.forEach(w => lines.push(`void On_${sanitize(w.name)}_Clicked(void);`));
    lines.push(``);
    lines.push(`// Implementation in ${sanitize('library')}.c`);
    return lines.join('\n');
  }

  // OnStart handler (implementation for non-library types)
  if (onStartNode) {
    lines.push(`void OnStart(void) {`);
    const next = findNextNode(onStartNode.id, 'exec');
    if (next) lines.push(generateNodeCode(next).trimEnd());
    lines.push(`}`);
    lines.push(``);
  }

  // Plugin preMain (defines entry point or adds code before main)
  if (plugin.preMain) {
    plugin.preMain.split('\n').forEach(l => { if (l.trim()) lines.push(l); });
    lines.push(``);
  }
  // Plugin postMain (closes entry point for replacesMain plugins, or adds to main body)
  if (plugin.replacesMain) {
    if (plugin.postMain) {
      plugin.postMain.split('\n').forEach(l => { if (l.trim()) lines.push(l); });
      lines.push(``);
    }
    // Don't generate a separate main() — plugin provides its own entry point
    return lines.join('\n');
  }

  // standard main
  lines.push(`int main(void) {`);

  if (raylib) {
    lines.push(`    InitWindow(SCREEN_WIDTH, SCREEN_HEIGHT, "C-Builder App");`);
    lines.push(`    SetTargetFPS(60);`);
    lines.push(``);
  }
  if (cimgui) {
    lines.push(`    if (!glfwInit()) return 1;`);
    lines.push(`    GLFWwindow* window = glfwCreateWindow(SCREEN_WIDTH, SCREEN_HEIGHT, "C-Builder App", NULL, NULL);`);
    lines.push(`    if (!window) { glfwTerminate(); return 1; }`);
    lines.push(`    glfwMakeContextCurrent(window);`);
    lines.push(`    glfwSwapInterval(1);`);
    lines.push(``);
    lines.push(`    igCreateContext(NULL);`);
    lines.push(`    ImGui_ImplGlfw_InitForOpenGL(window, true);`);
    lines.push(`    ImGui_ImplOpenGL3_Init("#version 130");`);
    lines.push(``);
  }

  if (onStartNode) {
    lines.push(`    OnStart();`);
    lines.push(``);
  }

  // Plugin postMain (injected at the start of main body)
  if (plugin.postMain) {
    plugin.postMain.split('\n').forEach(l => { if (l.trim()) lines.push(`    ${l}`); });
    lines.push(``);
  }

  if (raylib) {
    lines.push(`    while (!WindowShouldClose()) {`);
    lines.push(`        BeginDrawing();`);
    lines.push(`        ClearBackground(RAYWHITE);`);
    lines.push(``);

    widgets.forEach(w => {
      const x = Math.round(w.x);
      const y = Math.round(w.y);
      const width = prop(w.properties.width, 100);
      const height = prop(w.properties.height, 40);
      const text = prop<string>(w.properties.text, w.name);
      const sname = sanitize(w.name);

      if (w.type === 'Button') {
        const color = hexToRaylibColor(prop<string>(w.properties.color, '#007bff'));
        lines.push(`        // Button: ${w.name}`);
        lines.push(`        Rectangle rect_${sname} = { ${x}, ${y}, ${width}, ${height} };`);
        lines.push(`        if (CheckCollisionPointRec(GetMousePosition(), rect_${sname})) {`);
        lines.push(`            DrawRectangleRec(rect_${sname}, MAROON);`);
        lines.push(`            if (IsMouseButtonPressed(MOUSE_LEFT_BUTTON)) On_${sname}_Clicked();`);
        lines.push(`        } else {`);
        lines.push(`            DrawRectangleRec(rect_${sname}, ${color});`);
        lines.push(`        }`);
        lines.push(`        DrawText("${text}", ${x} + 10, ${y} + 10, 20, WHITE);`);
        lines.push(``);

      } else if (w.type === 'Label') {
        lines.push(`        // Label: ${w.name}`);
        lines.push(`        DrawText("${text}", ${x}, ${y}, 20, DARKGRAY);`);
        lines.push(``);

      } else if (w.type === 'TextField') {
        lines.push(`        // TextField: ${w.name}`);
        lines.push(`        Rectangle tf_${sname} = { ${x}, ${y}, ${width}, ${height} };`);
        lines.push(`        DrawRectangleLinesEx(tf_${sname}, 1, GRAY);`);
        lines.push(`        if (CheckCollisionPointRec(GetMousePosition(), tf_${sname}) && IsMouseButtonPressed(MOUSE_LEFT_BUTTON)) {`);
        lines.push(`            // TextField focused (implement focus logic as needed)`);
        lines.push(`        }`);
        lines.push(`        DrawText(${sname}_buf, ${x} + 4, ${y} + 10, 18, DARKGRAY);`);
        lines.push(``);

      } else if (w.type === 'Slider') {
        const min = prop(w.properties.min, 0);
        const max = prop(w.properties.max, 100);
        lines.push(`        // Slider: ${w.name}`);
        lines.push(`        ${sname}_value = GuiSlider((Rectangle){ ${x}, ${y}, ${width}, ${height} }, "${min}", "${max}", ${sname}_value, ${min}, ${max});`);
        lines.push(``);
      }
    });

    lines.push(`        EndDrawing();`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    CloseWindow();`);

  } else if (cimgui) {
    lines.push(`    while (!glfwWindowShouldClose(window)) {`);
    lines.push(`        glfwPollEvents();`);
    lines.push(`        ImGui_ImplOpenGL3_NewFrame();`);
    lines.push(`        ImGui_ImplGlfw_NewFrame();`);
    lines.push(`        igNewFrame();`);
    lines.push(``);

    widgets.forEach(w => {
      const text = prop<string>(w.properties.text, w.name);
      const sname = sanitize(w.name);

      if (w.type === 'Button') {
        lines.push(`        if (igButton("${text}", (ImVec2){${prop(w.properties.width, 100)}, ${prop(w.properties.height, 40)}})) {`);
        lines.push(`            On_${sname}_Clicked();`);
        lines.push(`        }`);
        lines.push(``);

      } else if (w.type === 'Label') {
        lines.push(`        igText("${text}");`);
        lines.push(``);

      } else if (w.type === 'TextField') {
        lines.push(`        igInputText("${text}", ${sname}_buf, sizeof(${sname}_buf), 0);`);
        lines.push(``);

      } else if (w.type === 'Slider') {
        const min = prop(w.properties.min, 0);
        const max = prop(w.properties.max, 100);
        lines.push(`        igSliderFloat("${text}", &${sname}_value, ${min}, ${max}, "%.1f", 0);`);
        lines.push(``);
      }
    });

    lines.push(`        igRender();`);
    lines.push(`        ImGui_ImplOpenGL3_RenderDrawData(igGetDrawData());`);
    lines.push(`        glfwSwapBuffers(window);`);
    lines.push(`    }`);
    lines.push(``);

  } else {
    // CLI mode: no raylib, just print
    lines.push(`    printf("C-Builder CLI App\\n");`);
    lines.push(`    printf("================\\n");`);
    lines.push(``);
  }

  lines.push(`    return 0;`);
  lines.push(`}`);

  return lines.join('\n');
};
