const GH_API = 'https://api.github.com';

const CLIENT_ID = import.meta.env.VITE_GITHUB_CLIENT_ID as string;
const OAUTH_SCOPE = 'repo';

export function startOAuthFlow() {
  const state = crypto.randomUUID();
  sessionStorage.setItem('oauth_state', state);
  const params = new URLSearchParams({
    client_id: CLIENT_ID,
    scope: OAUTH_SCOPE,
    redirect_uri: window.location.origin,
    state,
  });
  window.location.href = `https://github.com/login/oauth/authorize?${params}`;
}

export async function exchangeCodeForToken(code: string): Promise<string> {
  const res = await fetch('/api/github/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ code }),
  });
  const body = await res.json() as { access_token?: string; error?: string };
  if (!res.ok) throw new Error(body.error ?? 'Token exchange failed (check that server is running on port 3001)');
  return body.access_token!;
}

export async function getAuthenticatedUser(token: string) {
  const res = await fetch(`${GH_API}/user`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) throw new Error('Failed to fetch user');
  return res.json() as Promise<{ login: string; avatar_url: string }>;
}

const ghFetch = (token: string, path: string, opts: RequestInit = {}) =>
  fetch(`${GH_API}${path}`, {
    ...opts,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      ...(opts.headers ?? {}),
    },
  });

const CI_WORKFLOW = `name: Build C App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install raylib deps
        run: sudo apt-get install -y libraylib-dev || true
      - name: Compile
        run: gcc main.c -o app -lraylib -lm -lpthread -ldl -lrt -lX11 2>&1 || gcc main.c -o app -lm 2>&1
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: c-builder-app
          path: app
`;

export async function deleteRepo(token: string, login: string, repoName: string): Promise<void> {
  const res = await ghFetch(token, `/repos/${login}/${repoName}`, { method: 'DELETE' });
  if (!res.ok && res.status !== 404) {
    const err = await res.json() as { message: string };
    throw new Error(`Delete repo failed: ${err.message}`);
  }
}

export async function compileOnGitHub(
  token: string,
  login: string,
  code: string,
  projectName: string,
  prevRepoName?: string,
): Promise<{ url: string; repoName: string }> {
  // Delete previous build repo if exists
  if (prevRepoName) {
    await deleteRepo(token, login, prevRepoName);
  }

  const repoName = `c-builder-${projectName}-${Date.now()}`;

  // 1. Create repo
  const createRes = await ghFetch(token, '/user/repos', {
    method: 'POST',
    body: JSON.stringify({
      name: repoName,
      private: false,
      auto_init: false,
      description: 'Generated by C-Builder',
    }),
  });
  if (!createRes.ok) {
    const err = await createRes.json() as { message: string };
    throw new Error(`Create repo failed: ${err.message}`);
  }

  const repo = await createRes.json() as { default_branch: string };

  // 2. Create initial commit with both files via Git Trees/Commits API
  // (avoids `workflow` scope requirement of Contents API for .github/workflows/ paths)

  // 2a. Create blobs
  const blob = (content: string) =>
    ghFetch(token, `/repos/${login}/${repoName}/git/blobs`, {
      method: 'POST',
      body: JSON.stringify({ content, encoding: 'utf-8' }),
    }).then(r => r.json() as Promise<{ sha: string }>);

  const [mainBlob, workflowBlob] = await Promise.all([
    blob(code),
    blob(CI_WORKFLOW),
  ]);

  // 2b. Create tree with both files
  const treeRes = await ghFetch(token, `/repos/${login}/${repoName}/git/trees`, {
    method: 'POST',
    body: JSON.stringify({
      tree: [
        { path: 'main.c', mode: '100644', type: 'blob', sha: mainBlob.sha },
        { path: '.github/workflows/build.yml', mode: '100644', type: 'blob', sha: workflowBlob.sha },
      ],
    }),
  });
  if (!treeRes.ok) {
    const err = await treeRes.json() as { message: string };
    throw new Error(`Create tree failed: ${err.message}`);
  }
  const tree = await treeRes.json() as { sha: string };

  // 2c. Create commit
  const commitRes = await ghFetch(token, `/repos/${login}/${repoName}/git/commits`, {
    method: 'POST',
    body: JSON.stringify({
      message: 'Add generated C code with CI workflow',
      tree: tree.sha,
      parents: [],
    }),
  });
  if (!commitRes.ok) {
    const err = await commitRes.json() as { message: string };
    throw new Error(`Create commit failed: ${err.message}`);
  }
  const commit = await commitRes.json() as { sha: string };

  // 2d. Update HEAD
  const refRes = await ghFetch(token, `/repos/${login}/${repoName}/git/refs/heads/${repo.default_branch}`, {
    method: 'PATCH',
    body: JSON.stringify({ sha: commit.sha }),
  });
  if (!refRes.ok) {
    const err = await refRes.json() as { message: string };
    throw new Error(`Update ref failed: ${err.message}`);
  }

  return { url: `https://github.com/${login}/${repoName}/actions`, repoName };
}
