const GH_API = 'https://api.github.com';

const CLIENT_ID = import.meta.env.VITE_GITHUB_CLIENT_ID as string;
const OAUTH_SCOPE = 'repo';

export function startOAuthFlow() {
  const state = crypto.randomUUID();
  sessionStorage.setItem('oauth_state', state);
  const params = new URLSearchParams({
    client_id: CLIENT_ID,
    scope: OAUTH_SCOPE,
    redirect_uri: window.location.origin,
    state,
  });
  window.location.href = `https://github.com/login/oauth/authorize?${params}`;
}

export async function exchangeCodeForToken(code: string): Promise<string> {
  const res = await fetch('/api/github/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ code }),
  });
  const body = await res.json() as { access_token?: string; error?: string };
  if (!res.ok) throw new Error(body.error ?? 'Token exchange failed (check that server is running on port 3001)');
  return body.access_token!;
}

export async function getAuthenticatedUser(token: string) {
  const res = await fetch(`${GH_API}/user`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) throw new Error('Failed to fetch user');
  return res.json() as Promise<{ login: string; avatar_url: string }>;
}

const ghFetch = (token: string, path: string, opts: RequestInit = {}) =>
  fetch(`${GH_API}${path}`, {
    ...opts,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      ...(opts.headers ?? {}),
    },
  });

const b64 = (s: string) => btoa(unescape(encodeURIComponent(s)));

const CI_WORKFLOW = `name: Build C App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install raylib deps
        run: sudo apt-get install -y libraylib-dev || true
      - name: Compile
        run: gcc main.c -o app -lraylib -lm -lpthread -ldl -lrt -lX11 2>&1 || gcc main.c -o app -lm 2>&1
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: c-builder-app
          path: app
`;

export async function deleteRepo(token: string, login: string, repoName: string): Promise<void> {
  const res = await ghFetch(token, `/repos/${login}/${repoName}`, { method: 'DELETE' });
  if (!res.ok && res.status !== 404) {
    const err = await res.json() as { message: string };
    throw new Error(`Delete repo failed: ${err.message}`);
  }
}

export async function compileOnGitHub(
  token: string,
  login: string,
  code: string,
  projectName: string,
  prevRepoName?: string,
): Promise<{ url: string; repoName: string }> {
  // Delete previous build repo if exists
  if (prevRepoName) {
    await deleteRepo(token, login, prevRepoName);
  }

  const repoName = `c-builder-${projectName}-${Date.now()}`;

  // 1. Create repo
  const createRes = await ghFetch(token, '/user/repos', {
    method: 'POST',
    body: JSON.stringify({
      name: repoName,
      private: false,
      auto_init: true,
      description: 'Generated by C-Builder',
    }),
  });
  if (!createRes.ok) {
    const err = await createRes.json() as { message: string };
    throw new Error(`Create repo failed: ${err.message}`);
  }

  // 2. Push main.c via Contents API (works with repo scope)
  const pushFile = (path: string, content: string) =>
    ghFetch(token, `/repos/${login}/${repoName}/contents/${path}`, {
      method: 'PUT',
      body: JSON.stringify({
        message: `Add ${path}`,
        content: b64(content),
      }),
    });

  const mainRes = await pushFile('main.c', code);
  if (!mainRes.ok) {
    const err = await mainRes.json() as { message: string };
    throw new Error(`Push main.c failed: ${err.message}`);
  }

  // 3. Push CI workflow (may fail if token lacks workflow scope — non-fatal)
  const workflowRes = await pushFile('.github/workflows/build.yml', CI_WORKFLOW);
  if (!workflowRes.ok) {
    const err = await workflowRes.json() as { message: string };
    console.warn('Workflow push skipped:', err.message);
  }

  return { url: `https://github.com/${login}/${repoName}/actions`, repoName };
}
